package com.old.silence.auth.center.domain.model;


import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.auth.center.enums.ConfigItemFormatType;
import com.old.silence.auth.center.enums.ConfigItemType;
import com.old.silence.auth.center.enums.NameSpaceStatus;

import java.math.BigInteger;

public class ConfigItem extends AbstractAutoGeneratedIdAuditable<BigInteger> {


    private BigInteger configEnvironmentId;

    private String namespaceId;

    private NameSpaceStatus namespaceStatus;

    private ConfigItemFormatType formatType;

    /**
     * 配置项类型
     */
    private ConfigItemType type;

    /**
     * 配置项值
     */
    private String oldContent;

    /**
     * 配置项值
     */
    private String content;

    private String md5;

    public BigInteger getConfigEnvironmentId() {
        return configEnvironmentId;
    }

    public void setConfigEnvironmentId(BigInteger configEnvironmentId) {
        this.configEnvironmentId = configEnvironmentId;
    }

    public String getNamespaceId() {
        return namespaceId;
    }

    public void setNamespaceId(String namespaceId) {
        this.namespaceId = namespaceId;
    }

    public NameSpaceStatus getNamespaceStatus() {
        return namespaceStatus;
    }

    public void setNamespaceStatus(NameSpaceStatus namespaceStatus) {
        this.namespaceStatus = namespaceStatus;
    }

    public ConfigItemFormatType getFormatType() {
        return formatType;
    }

    public void setFormatType(ConfigItemFormatType formatType) {
        this.formatType = formatType;
    }

    public ConfigItemType getType() {
        return type;
    }

    public void setType(ConfigItemType type) {
        this.type = type;
    }

    public String getOldContent() {
        return oldContent;
    }

    public void setOldContent(String oldContent) {
        this.oldContent = oldContent;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }
}