package com.old.silence.auth.center.domain.model;


import com.baomidou.mybatisplus.annotation.TableField;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.auth.center.enums.ConfigEnvironmentType;

import java.math.BigInteger;

public class ConfigEnvironment extends AbstractAutoGeneratedIdAuditable<BigInteger> {


    private BigInteger configComponentId;

    /**
     * 配置项值
     */
    private String name;

    /**
     * 环境名称
     */
    private String displayName;

    /**
     * 配置项类型
     */
    private ConfigEnvironmentType envType;

    /**
     * 配置项状态
     */
    @TableField("is_display")
    private Boolean display;

    public BigInteger getConfigComponentId() {
        return configComponentId;
    }

    public void setConfigComponentId(BigInteger configComponentId) {
        this.configComponentId = configComponentId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public ConfigEnvironmentType getEnvType() {
        return envType;
    }

    public void setEnvType(ConfigEnvironmentType envType) {
        this.envType = envType;
    }

    public Boolean getDisplay() {
        return display;
    }

    public void setDisplay(Boolean display) {
        this.display = display;
    }
}