package com.old.silence.auth.center.domain.model;


import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

public class ConfigSubsystem extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    /**
     * 子系统名称
     */
    private String name;

    /**
     * 子系统编码
     */
    private String code;

    /**
     * 子系统描述
     */
    private String description;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}