package com.old.silence.auth.center.domain.model;

import jakarta.persistence.OneToMany;

import java.math.BigInteger;
import java.util.List;
import java.util.Map;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.auth.center.enums.MenuType;
import com.old.silence.auth.center.enums.ModuleType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;
import com.old.silence.data.commons.handler.StringToMapHandler;

@TableName("sys_menu")
public class Menu extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger, Boolean> {

    /**
     * 父菜单ID
     */
    private BigInteger parentId;

    /**
     * 菜单名称
     */
    private String name;

    /**
     * 菜单类型：1-目录，2-菜单，3-按钮
     */
    private MenuType type;

    /**
     * 模块类型
     */
    private ModuleType moduleType;


    /**
     * 路由路径
     */
    private String path;

    /**
     * 组件路径
     */
    private String component;

    private String redirect;

    /**
     * 源数据
     */
    @TableField(typeHandler = StringToMapHandler.class)
    private Map<String, Object> meta;

    /**
     * 显示顺序
     */
    private Long sort;

    /**
     * 状态：0-禁用，1-启用
     */
    private Boolean status;

    @OneToMany(mappedBy = "menu")
    private List<RoleMenu> roleMenus;

    public BigInteger getParentId() {
        return parentId;
    }

    public void setParentId(BigInteger parentId) {
        this.parentId = parentId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public MenuType getType() {
        return type;
    }

    public void setType(MenuType type) {
        this.type = type;
    }

    public ModuleType getModuleType() {
        return moduleType;
    }

    public void setModuleType(ModuleType moduleType) {
        this.moduleType = moduleType;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getComponent() {
        return component;
    }

    public void setComponent(String component) {
        this.component = component;
    }

    public String getRedirect() {
        return redirect;
    }

    public void setRedirect(String redirect) {
        this.redirect = redirect;
    }

    public Map<String, Object> getMeta() {
        return meta;
    }

    public void setMeta(Map<String, Object> meta) {
        this.meta = meta;
    }

    public Long getSort() {
        return sort;
    }

    public void setSort(Long sort) {
        this.sort = sort;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public List<RoleMenu> getRoleMenus() {
        return roleMenus;
    }

    public void setRoleMenus(List<RoleMenu> roleMenus) {
        this.roleMenus = roleMenus;
    }
}