package com.old.silence.auth.center.domain.model;


import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

import java.math.BigInteger;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;


@TableName("sys_role_menu")
public class RoleMenu extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    /**
     * 角色ID
     */
    private BigInteger roleId;

    /**
     * 菜单ID
     */
    private BigInteger menuId;

    @ManyToOne(optional = false)
    @JoinColumn(name = "role_id", referencedColumnName = "id")
    private Role role;

    @ManyToOne(optional = false)
    @JoinColumn(name = "menu_id", referencedColumnName = "id")
    private Menu menu;

    public RoleMenu() {
    }

    public RoleMenu(BigInteger roleId, BigInteger menuId) {
        this.roleId = roleId;
        this.menuId = menuId;
    }

    public BigInteger getRoleId() {
        return roleId;
    }

    public void setRoleId(BigInteger roleId) {
        this.roleId = roleId;
    }

    public BigInteger getMenuId() {
        return menuId;
    }

    public void setMenuId(BigInteger menuId) {
        this.menuId = menuId;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public Menu getMenu() {
        return menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }
}